ci: update generate_tf_state.yaml

diff --git a/.github/workflows/generate_tf_state.yaml b/.github/workflows/generate_tf_state.yaml
--- a/.github/workflows/generate_tf_state.yaml
+++ b/.github/workflows/generate_tf_state.yaml
@@ -11,7 +11,6 @@ on:
       name_prefix:
         description: "Prefix name (used for adding prefix to resources)"
         required: true
-        default: "eat"
         type: string
 
 jobs:
@@ -81,47 +80,63 @@ jobs:
             case "$az_type" in
               microsoft.compute/disks)
                 tf_type="azurerm_managed_disk"
+                tf_block="main"
                 ;;
               microsoft.compute/virtualmachines)
                 tf_type="azurerm_virtual_machine"
+                tf_block="main"
                 ;;
               microsoft.storage/storageaccounts)
                 tf_type="azurerm_storage_account"
+                tf_block="main"
                 ;;
               microsoft.network/virtualnetworks)
                 tf_type="azurerm_virtual_network"
+                tf_block="main"
                 ;;
               microsoft.network/networkinterfaces)
                 tf_type="azurerm_network_interface"
+                tf_block="main"
                 ;;
               microsoft.network/publicipaddresses)
                 tf_type="azurerm_public_ip"
+                tf_block="main"
                 ;;
               microsoft.sql/servers)
                 tf_type="azurerm_mssql_server"
+                tf_block="main"
+                ;;
+              microsoft.sql/servers/firewallrules)
+                tf_type="azurerm_mssql_firewall_rule"
+                tf_block="allow_all"
                 ;;
               microsoft.sql/servers/databases)
                 tf_type="azurerm_mssql_database"
+                tf_block="sql_database"
                 ;;
               microsoft.web/sites)
                 tf_type="azurerm_app_service"
+                tf_block="apps"
                 ;;
               microsoft.web/serverfarms)
                 tf_type="azurerm_app_service_plan"
+                tf_block="main"
                 ;;
               microsoft.managedidentity/userassignedidentities)
                 tf_type="azurerm_user_assigned_identity"
+                tf_block="main"
                 ;;
               # add more mappings here as needed
               *)
                 tf_type=""
+                tf_block=""
                 ;;
             esac
             echo "Terraform Type: $tf_type"
 
             if [ -n "$tf_type" ]; then
               echo "Importing $tf_type.$tf_name from $id"
-              terraform import "$tf_type.main" "$id" || echo "⚠️ Import failed for $id"
+              terraform import "$tf_type.$tf_block" "$id" || echo "⚠️ Import failed for $id"
             else
               echo "⚠️ No Terraform type mapping for Azure type: $az_type"
             fi
